package MyPack;

import java.awt.Color;
import java.awt.Font;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.LineBorder;

import UI.UI_DangKy;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Admin
 */
public class GUI_LOGIN extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	private JTextField txtUser;
	private JPasswordField txtPass;
	public boolean checkLogin = false;
	public String database,user,pass;
	public static String maDocGia;
    /**
     * Creates new form GUI_LOGIN
     */
    public GUI_LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
		JLabel lblNewLabel = new JLabel("Login");
		lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 35));
		lblNewLabel.setBounds(0, 5, 1264, 152);
		lblNewLabel.setBorder(new LineBorder(Color.RED, 3));
		getContentPane().add(lblNewLabel);
		
		setBounds(100, 100, 1264, 776);
		getContentPane().setLayout(null);
		JPanel panel = new JPanel();
		panel.setBorder(new LineBorder(new Color(0, 255, 255), 2, true));
		panel.setBounds(71, 156, 1122, 487);
		getContentPane().add(panel);
		panel.setLayout(null);
		
		txtUser = new JTextField();
		txtUser.setFont(new Font("Tahoma", Font.PLAIN, 30));
		txtUser.setColumns(10);
		txtUser.setBounds(164, 118, 793, 43);
		panel.add(txtUser);
		
		txtPass = new JPasswordField();
		txtPass.setFont(new Font("Tahoma", Font.PLAIN, 30));
		txtPass.setBounds(164, 292, 793, 43);
		panel.add(txtPass);
		
		JButton btnNewButton = new JButton("Đăng nhập");
		btnNewButton.setBounds(453, 372, 167, 49);
		panel.add(btnNewButton);
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				btnloginActionPerformed(e);
			}
		});
		
		btnNewButton.setFont(new Font("Tahoma", Font.PLAIN, 20));
		
		JButton btnngK = new JButton("Đăng kí");
		btnngK.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				UI_DangKy login = new UI_DangKy();
            	setVisible(false);
            	login.setVisible(true);
			}
		});
		btnngK.setFont(new Font("Tahoma", Font.PLAIN, 20));
		btnngK.setBounds(1093, 682, 147, 39);
		getContentPane().add(btnngK);
    }
    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String user,pass;
        user = txtUser.getText();
        pass= String.valueOf(txtPass.getPassword());
        try {
            // Kết nối đến cơ sở dữ liệu
            Connection connection = DatabaseService.GetConnection();
            CallableStatement callableStatement = connection.prepareCall("{call Check_Login(?, ?, ?, ?)}");
            callableStatement.setString(1, user);
            callableStatement.setString(2, pass);
            callableStatement.registerOutParameter(3, java.sql.Types.INTEGER);
            callableStatement.registerOutParameter(4, java.sql.Types.NCHAR);
            callableStatement.execute();
            
            int quyen = callableStatement.getInt(3);
            maDocGia = callableStatement.getString(4);
            if (quyen != -1) {
                // Đăng nhập thành công
                JOptionPane.showMessageDialog(null, "Đăng nhập thành công!");
                if(quyen == 0) {
                    MainAdmin_Form adminForm = new MainAdmin_Form();
                    setVisible(false);
                    adminForm.setVisible(true);
                }else
                {
                	Main_Form mainForm = new Main_Form();
                	setVisible(false);
                	mainForm.setVisible(true);
                }
            } else {
                // Đăng nhập thất bại
                JOptionPane.showMessageDialog(null, "Đăng nhập không thành công! Vui lòng kiểm tra lại tên đăng nhập và mật khẩu.");
            }
            DatabaseService.CloseConnection();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi thực hiện đăng nhập!");
        }
    }
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
}
